Add --existing <ipfs-url> option
License: MIT
Signed-off-by: Christian Couder <chriscool@tuxfamily.org>

diff --git a/git-ipfs-rehost b/git-ipfs-rehost
--- a/git-ipfs-rehost
+++ b/git-ipfs-rehost
@@ -1,7 +1,7 @@
 #!/bin/sh
 # git-rehost-ipfs - rehost a git repo on ipfs
 
-USAGE="usage: $0 [--unpack] <git-repo> [<name>]"
+USAGE="usage: $0 [--unpack] [--existing <ipfs-url>] <git-repo> [<name>]"
 
 die() {
 	echo >&2 "$@"
@@ -9,6 +9,7 @@ die() {
 }
 
 UNPACK=
+EXISTING=
 url=
 name=
 
@@ -19,6 +20,12 @@ do
 	case $1 in
 	--unpack)
 		UNPACK=1
+		shift
+		;;
+	--existing)
+		shift
+		EXISTING="$1"
+		[ -n "$EXISTING" ] || die "Invalid --existing argument\n$USAGE"
 		shift
 		;;
 	--*)
@@ -57,6 +64,40 @@ git clone --bare "$url" "$repo" || die "Could not clone '$url'"
 
 cd "$repo" || die "Could not cd into '$repo'"
 
+if [ -n "$EXISTING" ]
+then
+	case "$EXISTING" in
+	/ipfs/*)
+		# Ok
+		;;
+	*)
+		die "Bad --existing argument '$EXISTING'\n" \
+		    "It should start with '/ipfs/'"
+		;;
+	esac
+	echo "Getting packs from $EXISTING..."
+	ipfs ls "$EXISTING/objects/pack" >"$tohost/ls_existing_$name.log" ||
+		die "Could not ipfs ls '$EXISTING/objects/pack'"
+	while read phash psize pname
+	do
+		case "$pname" in
+		*\.pack)
+			# We use </dev/null to avoid problems because stdin is opened,
+			# as we are reading from a file in the enclosing while loop.
+			ipfs cat "$EXISTING/objects/pack/$pname" >"objects/pack/$pname" </dev/null ||
+				die "Could not ipfs cat '$EXISTING/objects/pack/$pname'"
+			pidx=$(echo "$pname" | sed -e 's/\.pack$/.idx/')
+			ipfs cat "$EXISTING/objects/pack/$pidx" >"objects/pack/$pidx" </dev/null ||
+				die "Could not ipfs cat '$EXISTING/objects/pack/$pidx'"
+			pkeep=$(echo "$pname" | sed -e 's/\.pack$/.keep/')
+			touch "objects/pack/$pkeep"
+			;;
+		*)
+			;;
+		esac
+	done <"$tohost/ls_existing_$name.log"
+fi
+
 if [ "$UNPACK" = 1 ]
 then
 	if ls objects/pack/*.pack >/dev/null 2>&1
@@ -76,7 +117,7 @@ else
 	# This should pack and remove unwanted and unneeded objects
 	git gc || die "Could not garbage collect"
 
-	# Create .keep files so that the .pack will be kept
+	# Create .keep files so that the .pack files will be kept
 	for pack in objects/pack/*.pack
 	do
 		keep=$(echo "$pack" | sed -e 's/\.pack$/.keep/')
