Further rework unpacking
Work around globing not working after "<" with some shells.
And simplify "./*.pack" into just "*.pack".

License: MIT
Signed-off-by: Christian Couder <chriscool@tuxfamily.org>

diff --git a/git-ipfs-rehost b/git-ipfs-rehost
--- a/git-ipfs-rehost
+++ b/git-ipfs-rehost
@@ -24,10 +24,12 @@ git clone --bare "$url" "$repo" || die "Could not clone '$url'"
 
 cd "$repo" || die "Could not cd into '$repo'"
 
-if ls "$repo/objects/pack/"*.pack 1> /dev/null 2>&1; then
+if ls objects/pack/*.pack >/dev/null 2>&1; then
 	mv objects/pack/*.pack . || die "Could not move packs"
-	git unpack-objects < ./*.pack || die "Could not unpack packs"
-	rm ./*.pack || die "Could not remove packs"
+	# Unfortunately some shells like dash don't perform globing
+	# after "<", so "git unpack-objects < *.pack" doesn't work.
+	cat *.pack | git unpack-objects || die "Could not unpack packs"
+	rm -f *.pack || die "Could not remove packs"
 fi
 
 git update-server-info || die "Could not update-server-info"
